export type RootStackParamList = {
  Form: {
    id?: number;
    nome_medicao?: string;
    area?: number;
    distRenques?: number;
    numLinhasRenque?: number;
    distLinhas?: number;
    distArvores?: number;
    erroPermitido?: number;
    parcelaPreliminar1?: number | null;
    parcelaPreliminar2?: number | null;
    parcelaPreliminar3?: number | null;
    parcelaPreliminar4?: number | null;
    parcelaPreliminar5?: number | null;
    status?: 'incompleto' | 'completo';
    created_at?: string;
    updated_at?: string;
    totalParcelasRequeridas?: number;
  };
  List: undefined;
  About: undefined;
  Settings: undefined;
  MainTabs: {
  screen: keyof MainTabsParamList;
  params?: MainTabsParamList[keyof MainTabsParamList];
};
  Edit: {
    id: number;
    nome_medicao: string;
    area: number;
    distRenques: number;
    numLinhasRenque: number;
    distLinhas: number;
    distArvores: number;
    erroPermitido: number;
    parcelaPreliminar1: number | null;
    parcelaPreliminar2: number | null;
    parcelaPreliminar3: number | null;
    parcelaPreliminar4: number | null;
    parcelaPreliminar5: number | null;
    status: 'incompleto' | 'completo';
    created_at?: string;
    updated_at?: string;
  };
  Result: {
    nome_medicao: string;
    area: number;
    distRenques: number;
    numLinhasRenque: number;
    distLinhas: number;
    distArvores: number;
    erroPermitido: number;
    parcelaPreliminar1: number;
    parcelaPreliminar2: number;
    parcelaPreliminar3: number;
    parcelaPreliminar4: number;
    parcelaPreliminar5: number;
    areaPorArvore: number;
    densidadeArborea: number;
    taxaOcupacaoSolo: number;
    totalArvores: number;
    dimensao1: number;
    dimensao2: number;
    areaTotal: number;
    densidadesPreliminares: number[];
    numParcelasCalculado: number;
    distanciaEntreParcelas: number;
    totalArvoresMonitoradas: number;
    numArvoreParcela: number;
    created_at?: string;
    updated_at?: string;
  };
};

export type MainTabsParamList = {
  List: undefined;
  Form: {
    id?: number;
    nome_medicao?: string;
    area?: number;
    distRenques?: number;
    numLinhasRenque?: number;
    distLinhas?: number;
    distArvores?: number;
    erroPermitido?: number;
    parcelaPreliminar1?: number | null;
    parcelaPreliminar2?: number | null;
    parcelaPreliminar3?: number | null;
    parcelaPreliminar4?: number | null;
    parcelaPreliminar5?: number | null;
    status?: 'incompleto' | 'completo';
    created_at?: string;
    updated_at?: string;
    totalParcelasRequeridas?: number;
  };
  Result: {
    nome_medicao: string;
    area: number;
    distRenques: number;
    numLinhasRenque: number;
    distLinhas: number;
    distArvores: number;
    erroPermitido: number;
    parcelaPreliminar1: number;
    parcelaPreliminar2: number;
    parcelaPreliminar3: number;
    parcelaPreliminar4: number;
    parcelaPreliminar5: number;
    areaPorArvore: number;
    densidadeArborea: number;
    taxaOcupacaoSolo: number;
    totalArvores: number;
    dimensao1: number;
    dimensao2: number;
    areaTotal: number;
    densidadesPreliminares: number[];
    numParcelasCalculado: number;
    distanciaEntreParcelas: number;
    totalArvoresMonitoradas: number;
    numArvoreParcela: number;
  };
  About: undefined;
  Settings: undefined;
};